<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27754" started-at="2019-11-10T14:01:54Z" finished-at="2019-11-10T14:02:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27754" started-at="2019-11-10T14:01:54Z" finished-at="2019-11-10T14:02:22Z">
      <class name="com.pagelibrary.com.ranford_bnk.TestExecution">
        <test-method status="PASS" signature="generate_report()[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="generate_report" is-config="true" duration-ms="203" started-at="2019-11-10T19:31:54Z" finished-at="2019-11-10T19:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generate_report -->
        <test-method status="PASS" signature="Send_method_To_report(java.lang.reflect.Method)[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="Send_method_To_report" is-config="true" duration-ms="0" started-at="2019-11-10T19:31:54Z" finished-at="2019-11-10T19:31:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.pagelibrary.com.ranford_bnk.TestExecution.verify_launch()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Send_method_To_report -->
        <test-method status="PASS" signature="verify_launch()[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="verify_launch" duration-ms="26665" started-at="2019-11-10T19:31:54Z" finished-at="2019-11-10T19:32:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_launch -->
        <test-method status="PASS" signature="save_report()[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="save_report" is-config="true" duration-ms="445" started-at="2019-11-10T19:32:21Z" finished-at="2019-11-10T19:32:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- save_report -->
        <test-method status="FAIL" signature="verify_login()[pri:1, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="verify_login" duration-ms="62" started-at="2019-11-10T19:32:21Z" finished-at="2019-11-10T19:32:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[verification of username field is failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: verification of username field is failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.pagelibrary.com.ranford_bnk.Reprository.login_TC(Reprository.java:89)
	at com.pagelibrary.com.ranford_bnk.TestExecution.verify_login(TestExecution.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login -->
        <test-method status="PASS" signature="Send_method_To_report(java.lang.reflect.Method)[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="Send_method_To_report" is-config="true" duration-ms="0" started-at="2019-11-10T19:32:21Z" finished-at="2019-11-10T19:32:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.pagelibrary.com.ranford_bnk.TestExecution.verify_login()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Send_method_To_report -->
        <test-method status="PASS" signature="save_report()[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="save_report" is-config="true" duration-ms="78" started-at="2019-11-10T19:32:21Z" finished-at="2019-11-10T19:32:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- save_report -->
        <test-method status="PASS" signature="save_report()[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="save_report" is-config="true" duration-ms="203" started-at="2019-11-10T19:32:21Z" finished-at="2019-11-10T19:32:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- save_report -->
        <test-method status="PASS" signature="Send_method_To_report(java.lang.reflect.Method)[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="Send_method_To_report" is-config="true" duration-ms="0" started-at="2019-11-10T19:32:21Z" finished-at="2019-11-10T19:32:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.pagelibrary.com.ranford_bnk.TestExecution.verify_btn()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Send_method_To_report -->
        <test-method status="FAIL" signature="verify_btn()[pri:2, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="verify_btn" duration-ms="0" started-at="2019-11-10T19:32:21Z" finished-at="2019-11-10T19:32:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[verification of login btn is failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: verification of login btn is failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.pagelibrary.com.ranford_bnk.Reprository.branch_btn(Reprository.java:121)
	at com.pagelibrary.com.ranford_bnk.TestExecution.verify_btn(TestExecution.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_btn -->
        <test-method status="PASS" signature="Send_method_To_report(java.lang.reflect.Method)[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="Send_method_To_report" is-config="true" duration-ms="0" started-at="2019-11-10T19:32:22Z" finished-at="2019-11-10T19:32:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.pagelibrary.com.ranford_bnk.TestExecution.verify_newbranch_btn()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Send_method_To_report -->
        <test-method status="FAIL" signature="verify_newbranch_btn()[pri:3, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="verify_newbranch_btn" duration-ms="31" started-at="2019-11-10T19:32:22Z" finished-at="2019-11-10T19:32:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[verification of newbranch btn is failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: verification of newbranch btn is failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.pagelibrary.com.ranford_bnk.Reprository.BranchCreation_TC(Reprository.java:138)
	at com.pagelibrary.com.ranford_bnk.TestExecution.verify_newbranch_btn(TestExecution.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_newbranch_btn -->
        <test-method status="PASS" signature="save_report()[pri:0, instance:com.pagelibrary.com.ranford_bnk.TestExecution@28d25987]" name="save_report" is-config="true" duration-ms="47" started-at="2019-11-10T19:32:22Z" finished-at="2019-11-10T19:32:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- save_report -->
      </class> <!-- com.pagelibrary.com.ranford_bnk.TestExecution -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
